###服务启动端口号
server:
  port: 9200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: www.product
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9009/eureka


    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true

