###服务端口号
server:
  port: 8100
###eureka 基本信息配置
spring:
  application:
    name: Eureka
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
    ###集群需要自己注册自己
    register-with-eureka: true
    ###集群需要检索服务
    fetch-registry: true